[libdefaults]
  default_realm = EXAMPLE.ORG
  dns_lookup_realm = false
  dns_lookup_kdc = false
  rdns = false
[realms]
  EXAMPLE.ORG = {
    kdc = 192.168.22.70
    admin_server = 192.168.22.70
    }
[domain_realm]
  .example.org = EXAMPLE.ORG
  example.org = EXAMPLE.ORG

